- name: update apt cache
  apt:
    update_cache: yes
    cache_valid_time: 86400
  become: true
  changed_when: false

- name: install build depends
  apt:
    pkg: "{{ item }}"
    state: present
    install_recommends: no
  with_items:
  - "{{ nodenv_apt_packages }}"
  become: true

- name: install extra build depends
  apt:
    pkg: "{{ item }}"
    state: present
    install_recommends: no
  with_items: "{{ nodenv_extra_depends }}"
  become: true
