---
- name: Create the list of NodeJS versions to installing.
  set_fact:
    nodenv_nodejs_versions: "{{ nodenv_nodejs_versions | default([]) }} + {{ [item.version] }}"
  with_items:
    - "{{ nodenv.nodejs }}"

- name: set tmp directory path
  set_fact: nodenv_tmpdir="{{ ansible_env.TMPDIR | default('/tmp') }}"
  when: nodenv_tmpdir is undefined